# Generated by Django 3.2.5 on 2021-12-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_cliente', '0001_initial'),
        ('datos_g', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('bolsa', models.IntegerField(primary_key=True, serialize=False)),
                ('mot', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_g.motivo', verbose_name='motivo')),
            ],
        ),
        migrations.CreateModel(
            name='Motivo_mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('bolsa', models.IntegerField()),
                ('seudo', models.OneToOneField(help_text='Codigo de barras', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base_cliente.bd_clie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fisico',
            fields=[
                ('bolsa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='fisico.bolsa')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_guia', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Total')),
                ('suma', models.IntegerField(blank=True, default=0, null=True)),
                ('destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('d_i', models.CharField(blank=True, max_length=15, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='guia')),
            ],
            options={
                'abstract': False,
            },
            bases=('fisico.bolsa', models.Model),
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=200)),
                ('id_motivo_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisico.motivo_mesa', verbose_name='motivo')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisico.fisico')),
            ],
            options={
                'verbose_name': 'inconsistencias',
                'verbose_name_plural': 'inconsistencias',
            },
        ),
    ]
