# Generated by Django 3.2.5 on 2021-08-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seudo', models.CharField(max_length=35)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Estado', models.BooleanField(default=True)),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia.guia')),
            ],
        ),
    ]
