# Generated by Django 3.2.5 on 2021-07-15 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bolsa', models.IntegerField()),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Estado', models.BooleanField(default=True)),
                ('Seudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_cliente.bd_clie')),
            ],
            options={
                'verbose_name': 'Fisico',
                'verbose_name_plural': 'Fisico',
                'unique_together': {('Bolsa', 'Seudo')},
            },
        ),
    ]
