# Generated by Django 3.2.5 on 2021-08-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0001_initial'),
        ('fisico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='seudo_pa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base_cliente.bd_clie'),
        ),
    ]
