# Generated by Django 3.2.5 on 2021-08-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='Seudo',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
