# Generated by Django 3.2.5 on 2021-07-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('bolsa', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
