# Generated by Django 3.2.5 on 2022-02-03 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos_g', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fisico', '0001_initial'),
        ('guia', '0001_initial'),
        ('courrier', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='id_motivo_m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisico.motivo_mesa', verbose_name='motivo'),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='mot',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_g.motivo', verbose_name='motivo'),
        ),
        migrations.AlterUniqueTogether(
            name='paquete',
            unique_together={('bolsa', 'seudo')},
        ),
        migrations.AddField(
            model_name='mesa',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisico.fisico'),
        ),
        migrations.AddField(
            model_name='fisico',
            name='cod_vis',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.cod_vis'),
        ),
        migrations.AddField(
            model_name='fisico',
            name='id_ciu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad', verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='fisico',
            name='id_est',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='fisico',
            name='mensajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courrier.courrier'),
        ),
        migrations.AddField(
            model_name='fisico',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fisico.proceso'),
        ),
    ]
