# Generated by Django 3.2.5 on 2021-11-12 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_guia_user'),
        ('fisico', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='id_est',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.estado', verbose_name='Estado'),
        ),
    ]
