# Generated by Django 3.2.5 on 2022-02-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisico',
            name='codigo',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='historicalfisico',
            name='codigo',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
