# Generated by Django 3.2.5 on 2022-02-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
