# Generated by Django 3.2.5 on 2021-07-28 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0002_bolsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsa',
            name='Seudo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fisico.seudo_muchos'),
            preserve_default=False,
        ),
    ]
