# Generated by Django 3.2.5 on 2022-02-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0003_alter_fisico_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisico',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='historicalfisico',
            name='imagen',
        ),
    ]
