# Generated by Django 3.2.5 on 2022-03-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0003_auto_20220317_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='fecha_planilla',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfisico',
            name='fecha_planilla',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
