# Generated by Django 3.2.5 on 2022-01-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0003_fisico_mensajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisico',
            name='est_planilla',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
