# Generated by Django 3.2.5 on 2022-02-10 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0004_alter_historicalguia_id_est'),
        ('fisico', '0003_auto_20220210_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='id_est',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalfisico',
            name='id_est',
            field=models.ForeignKey(blank=True, db_constraint=False, default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guia.estado', verbose_name='Estado'),
        ),
    ]
