# Generated by Django 3.2.5 on 2021-07-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0003_bolsa_seudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsa',
            name='Seudo',
        ),
        migrations.AddField(
            model_name='bolsa',
            name='Seudo',
            field=models.ManyToManyField(to='fisico.Seudo_muchos'),
        ),
    ]
