# Generated by Django 3.2.5 on 2021-11-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0004_mesa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'verbose_name': 'inconsistencias', 'verbose_name_plural': 'inconsistencias'},
        ),
    ]
