# Generated by Django 3.2.5 on 2021-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0004_auto_20210728_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='paquete',
            fields=[
                ('bolsa', models.IntegerField(primary_key=True, serialize=False)),
                ('Seudo', models.CharField(max_length=35)),
            ],
        ),
        migrations.DeleteModel(
            name='Bolsa',
        ),
        migrations.DeleteModel(
            name='Seudo_muchos',
        ),
    ]
