# Generated by Django 3.2.5 on 2022-03-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0006_auto_20220328_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='fecha_descargue',
            field=models.DateField(blank=True, null=True, verbose_name='Descargue'),
        ),
        migrations.AlterField(
            model_name='historicalfisico',
            name='fecha_descargue',
            field=models.DateField(blank=True, null=True, verbose_name='Descargue'),
        ),
    ]
