# Generated by Django 3.2.5 on 2021-07-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0006_auto_20210728_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='Bolsa',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
