# Generated by Django 3.2.5 on 2022-01-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0006_fisico_id_planilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='id_planilla',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
