# Generated by Django 3.2.5 on 2021-07-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0002_auto_20210728_1820'),
        ('fisico', '0007_alter_fisico_bolsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='Seudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_cliente.bd_clie'),
        ),
    ]
