# Generated by Django 3.2.5 on 2022-01-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0007_alter_fisico_id_planilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisico',
            name='fecha_planilla',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
