# Generated by Django 3.2.5 on 2021-07-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0008_alter_paquete_seudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='Seudo',
            field=models.CharField(max_length=35),
        ),
    ]
