# Generated by Django 3.2.5 on 2022-01-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0001_initial'),
        ('fisico', '0008_fisico_fecha_planilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='seudo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base_cliente.bd_clie'),
        ),
    ]
