# Generated by Django 3.2.5 on 2022-04-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0009_cobertura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsa',
            name='fecha_bolsa',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfisico',
            name='fecha_bolsa',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
