# Generated by Django 3.2.5 on 2022-05-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0011_auto_20220502_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='estado_destino',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalfisico',
            name='estado_destino',
            field=models.BooleanField(default=False),
        ),
    ]
