# Generated by Django 3.2.5 on 2022-06-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0012_auto_20220502_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisico',
            name='estado_img',
            field=models.CharField(blank=True, choices=[('E', 'ENTREGA'), ('D', 'ENTREGA DIGITALIZADA')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalfisico',
            name='estado_img',
            field=models.CharField(blank=True, choices=[('E', 'ENTREGA'), ('D', 'ENTREGA DIGITALIZADA')], max_length=1, null=True),
        ),
    ]
