# Generated by Django 3.2.5 on 2022-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0013_auto_20220609_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='estado_img',
            field=models.CharField(blank=True, choices=[('ENTREGA', 'ENTREGA'), ('ENTREGA_DIGITALIZADA', 'ENTREGA DIGITALIZADA')], max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfisico',
            name='estado_img',
            field=models.CharField(blank=True, choices=[('ENTREGA', 'ENTREGA'), ('ENTREGA_DIGITALIZADA', 'ENTREGA DIGITALIZADA')], max_length=22, null=True),
        ),
    ]
