# Generated by Django 3.2.5 on 2022-06-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0014_auto_20220609_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisico',
            name='estado_img',
            field=models.CharField(blank=True, choices=[('ENTREGA', 'ENTREGA'), ('ENTREGA_DIGITALIZADA', 'ENTREGA DIGITALIZADA')], max_length=22, null=True, verbose_name='gestion'),
        ),
        migrations.AlterField(
            model_name='historicalfisico',
            name='estado_img',
            field=models.CharField(blank=True, choices=[('ENTREGA', 'ENTREGA'), ('ENTREGA_DIGITALIZADA', 'ENTREGA DIGITALIZADA')], max_length=22, null=True, verbose_name='gestion'),
        ),
    ]
