# Generated by Django 3.2.5 on 2022-06-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0015_auto_20220610_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobertura',
            name='pdf_cobertura',
            field=models.FileField(blank=True, null=True, upload_to='pdf_cobertura'),
        ),
    ]
