# Generated by Django 3.2.5 on 2022-06-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0016_cobertura_pdf_cobertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='bolsa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cobertura_bolsa', serialize=False, to='fisico.bolsa'),
        ),
    ]
