# Generated by Django 3.2.5 on 2022-06-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0017_alter_cobertura_bolsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha fisico'),
        ),
    ]
