# Generated by Django 3.2.5 on 2022-06-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0018_alter_cobertura_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobertura',
            name='estado_mesa',
            field=models.BooleanField(default=False),
        ),
    ]
