# Generated by Django 3.2.5 on 2022-06-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0020_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
