# Generated by Django 3.2.5 on 2022-06-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0021_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='bolsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsapaquete', to='fisico.bolsa'),
        ),
    ]
