# Generated by Django 3.2.5 on 2022-06-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0008_franquicia'),
        ('fisico', '0022_alter_paquete_bolsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsa',
            name='id_est',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalfisico',
            name='id_est',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='argumento.estado', verbose_name='Estado'),
        ),
    ]
