# Generated by Django 3.2.5 on 2022-07-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0024_alter_fisico_mensajero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisico',
            name='estado_img',
        ),
        migrations.RemoveField(
            model_name='historicalfisico',
            name='estado_img',
        ),
    ]
