# Generated by Django 3.2.5 on 2022-01-17 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guia', '0003_alter_guia_options'),
        ('courrier', '0001_initial'),
        ('fisico', '0002_initial'),
        ('datos_g', '0004_alter_datos_g_seudo_dg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargue',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Planilla')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de entrega')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.courrier', verbose_name='Mensajero')),
            ],
            options={
                'verbose_name': 'Cargue',
                'verbose_name_plural': 'Cargue',
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha recepcion')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.estado')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisico.fisico')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_g.motivo')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.cargue')),
            ],
            options={
                'verbose_name': 'Recepcion',
                'verbose_name_plural': 'Recepciones',
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('cargue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruta.cargue', verbose_name='Planilla')),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fisico.fisico')),
            ],
            options={
                'ordering': ('guia__fecha', 'id'),
            },
        ),
        migrations.AddField(
            model_name='cargue',
            name='guia',
            field=models.ManyToManyField(through='ruta.Planilla', to='fisico.Fisico'),
        ),
    ]
