# Generated by Django 3.2.5 on 2021-12-23 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='full_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courrier.courrier', verbose_name='Mensajero'),
        ),
    ]
