# Generated by Django 3.2.5 on 2021-12-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programador',
        ),
    ]
