# Generated by Django 3.2.5 on 2022-01-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargue',
            name='full_name',
        ),
        migrations.AddField(
            model_name='cargue',
            name='full_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courrier.courrier', verbose_name='Mensajero'),
            preserve_default=False,
        ),
    ]
