# Generated by Django 3.2.5 on 2021-09-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_rename_fecha_cargue_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargue',
            name='bolsa',
        ),
    ]
