# Generated by Django 3.2.5 on 2022-01-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_auto_20220113_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planilla',
            options={},
        ),
    ]
