# Generated by Django 3.2.5 on 2021-12-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_planilla_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
