# Generated by Django 3.2.5 on 2021-12-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_delete_programador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lenguaje',
        ),
    ]
