# Generated by Django 3.2.5 on 2021-12-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0003_delete_lenguaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recep_guia',
        ),
    ]
