# Generated by Django 3.2.5 on 2022-01-17 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0003_alter_planilla_estados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.planilla'),
        ),
    ]
