# Generated by Django 3.2.5 on 2022-01-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0004_alter_recepcion_planilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='estados',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
