# Generated by Django 3.2.5 on 2021-12-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0004_planilla_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargue',
            name='pruebass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
