# Generated by Django 3.2.5 on 2022-01-18 14:30

import applications.guia.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0005_alter_planilla_estados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.planilla', verbose_name=applications.guia.models.Guia),
        ),
    ]
