# Generated by Django 3.2.5 on 2022-03-23 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0005_destino_sucursales'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='ruta.sucursales'),
            preserve_default=False,
        ),
    ]
