# Generated by Django 3.2.5 on 2021-09-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0005_alter_cargue_mensajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='bolsa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
