# Generated by Django 3.2.5 on 2022-03-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0006_destino_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='origen_destino',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
