# Generated by Django 3.2.5 on 2021-09-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0001_initial'),
        ('ruta', '0006_recepcion_bolsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia.motivo'),
        ),
    ]
