# Generated by Django 3.2.5 on 2022-01-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0006_alter_recepcion_planilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcion',
            name='planilla',
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.planilla'),
        ),
    ]
