# Generated by Django 3.2.5 on 2022-03-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0007_destino_origen_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='origen_destino',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
