# Generated by Django 3.2.5 on 2022-01-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0008_alter_recepcion_guia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='estados',
        ),
        migrations.AddField(
            model_name='planilla',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ruta.est_planilla'),
            preserve_default=False,
        ),
    ]
