# Generated by Django 3.2.5 on 2021-12-28 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
        ('ruta', '0008_auto_20211227_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargue',
            name='full_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courrier.courrier', verbose_name='Mensajero'),
            preserve_default=False,
        ),
    ]
