# Generated by Django 3.2.5 on 2022-01-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0009_auto_20220118_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='estado',
        ),
    ]
