# Generated by Django 3.2.5 on 2022-03-23 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0004_auto_20220317_1059'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ruta', '0009_alter_destino_guia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descargue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guia_descargue', to='fisico.fisico')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
