# Generated by Django 3.2.5 on 2022-01-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0010_remove_planilla_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='cont',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
