# Generated by Django 3.2.5 on 2021-12-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0002_initial'),
        ('ruta', '0010_auto_20211229_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargue',
            name='guia',
            field=models.ManyToManyField(through='ruta.Planilla', to='fisico.Fisico'),
        ),
    ]
