# Generated by Django 3.2.5 on 2022-03-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0010_descargue'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Destino'),
        ),
    ]
