# Generated by Django 3.2.5 on 2022-01-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0011_planilla_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='cont',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
