# Generated by Django 3.2.5 on 2022-01-20 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0007_alter_fisico_id_planilla'),
        ('ruta', '0012_alter_planilla_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planilla_filtro', to='fisico.fisico'),
        ),
    ]
