# Generated by Django 3.2.5 on 2022-03-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0012_descargue_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Destino'),
        ),
    ]
