# Generated by Django 3.2.5 on 2022-03-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0013_alter_destino_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descargue',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Descargue'),
        ),
    ]
