# Generated by Django 3.2.5 on 2022-01-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0003_auto_20220118_1553'),
        ('ruta', '0013_alter_planilla_guia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='estado',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.estado'),
        ),
    ]
