# Generated by Django 3.2.5 on 2022-03-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0014_alter_descargue_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='origen_destino',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
