# Generated by Django 3.2.5 on 2022-05-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0019_historicaldestino'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='estado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldestino',
            name='estado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
