# Generated by Django 3.2.5 on 2022-05-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0020_auto_20220502_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guia_destino', to='ruta.sucursales'),
        ),
    ]
