# Generated by Django 3.2.5 on 2022-05-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0021_alter_destino_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='historicaldestino',
            name='estado',
        ),
    ]
