# Generated by Django 3.2.5 on 2022-02-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('courrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='id_ciu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad', verbose_name='Ciudad'),
        ),
    ]
