# Generated by Django 3.2.5 on 2022-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='id_veg',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Id vehiculo'),
        ),
    ]
