# Generated by Django 3.2.5 on 2022-01-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='cel',
            field=models.CharField(max_length=12, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='d_i',
            field=models.CharField(max_length=12),
        ),
    ]
