# Generated by Django 3.2.5 on 2022-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('modelo', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
    ]
