# Generated by Django 3.2.5 on 2022-02-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0002_alter_courrier_id_ciu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='id_veh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.vehiculo', verbose_name='Datos vehiculo'),
        ),
    ]
