# Generated by Django 3.2.5 on 2022-02-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0003_alter_courrier_id_veh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrier',
            name='soat',
        ),
        migrations.RemoveField(
            model_name='courrier',
            name='tecnomecanica',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='soat',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tecnomecanica',
            field=models.BooleanField(default=False),
        ),
    ]
