# Generated by Django 3.2.5 on 2022-02-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0004_auto_20220203_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrier',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='courrier',
            name='tipo',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courrier.tipo_vehiculo', verbose_name='Tipo vehiculo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courrier.marca_vehiculo'),
        ),
    ]
