# Generated by Django 3.2.5 on 2022-02-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0005_auto_20220203_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='linea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courrier.linea_vehiculo'),
            preserve_default=False,
        ),
    ]
