# Generated by Django 3.2.5 on 2022-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0006_auto_20220203_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='d_i',
            field=models.CharField(max_length=12, verbose_name='Documento identidad'),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='dir',
            field=models.CharField(max_length=120, verbose_name='Direccion'),
        ),
    ]
