# Generated by Django 3.2.5 on 2021-08-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emision',
            fields=[
                ('t_emi', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Tipo emision')),
                ('emision', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Emision',
                'verbose_name_plural': 'Emision',
            },
        ),
        migrations.CreateModel(
            name='est_clie',
            fields=[
                ('id_est_clie', models.IntegerField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=35)),
                ('Descripcion', models.CharField(max_length=35)),
                ('Proceso', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pro', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Id producto')),
                ('producto', models.CharField(max_length=50)),
                ('Proceso', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=5, verbose_name='Tipos distribucion')),
                ('Homologacion', models.CharField(max_length=50)),
                ('id_clie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Id cliente')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto',
                'unique_together': {('id_pro', 'id_clie')},
            },
        ),
        migrations.CreateModel(
            name='bd_clie',
            fields=[
                ('Seudo', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('Archivo', models.CharField(blank=True, max_length=15, null=True)),
                ('Jornada', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=3, null=True)),
                ('D_i', models.IntegerField(blank=True, null=True, verbose_name='Documento de identidad')),
                ('Cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('Id_Proc', models.IntegerField(blank=True, null=True)),
                ('ofi', models.CharField(blank=True, max_length=8, null=True, verbose_name='Oficina')),
                ('Canal', models.CharField(blank=True, max_length=8, null=True)),
                ('Realz', models.CharField(blank=True, max_length=30, null=True, verbose_name='Realzador')),
                ('Tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('D_i_a', models.IntegerField(blank=True, null=True, verbose_name='Documento identidad autorizado')),
                ('Autor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autorizado')),
                ('Tarjeta', models.CharField(blank=True, max_length=30, null=True)),
                ('Codigo', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('Referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('convenio', models.CharField(blank=True, max_length=50, null=True)),
                ('id_serv', models.IntegerField(verbose_name='Id Servicio')),
                ('Bolsa', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('Id_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_cliente.producto', verbose_name='Id producto')),
                ('T_emi', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='base_cliente.emision', verbose_name='Tipo Emision')),
                ('id_clie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Id cliente')),
                ('id_est_clie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_cliente.est_clie', verbose_name='Id estado cliente ')),
            ],
            options={
                'verbose_name': 'Base Cliente',
                'verbose_name_plural': 'Base Cliente',
            },
        ),
    ]
