# Generated by Django 3.2.5 on 2022-02-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('argumento', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bd_clie',
            fields=[
                ('seudo_bd', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('archivo', models.CharField(blank=True, max_length=15, null=True)),
                ('jornada', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=3, null=True)),
                ('canal', models.CharField(blank=True, max_length=8, null=True)),
                ('realz', models.CharField(blank=True, max_length=30, null=True, verbose_name='Realzador')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('tarjeta', models.CharField(blank=True, max_length=30, null=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('convenio', models.CharField(blank=True, max_length=50, null=True)),
                ('id_serv', models.IntegerField(verbose_name='Id Servicio')),
                ('fecha', models.DateField()),
                ('sucursal', models.CharField(blank=True, max_length=50, null=True)),
                ('id_clie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Id cliente')),
                ('id_est_clie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.est_clie', verbose_name='Id estado cliente ')),
                ('nom_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argumento.nom_producto', verbose_name='Nombre del producto')),
                ('t_emi', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='argumento.emision', verbose_name='Tipo Emision')),
            ],
            options={
                'verbose_name': 'Base Cliente',
                'verbose_name_plural': 'Base Cliente',
            },
        ),
    ]
