# Generated by Django 3.2.5 on 2021-08-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd_clie',
            name='guia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
