# Generated by Django 3.2.5 on 2022-03-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd_clie',
            name='fisico',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
