# Generated by Django 3.2.5 on 2022-02-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0002_emision'),
        ('base_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_clie',
            name='t_emi',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='argumento.emision', verbose_name='Tipo Emision'),
        ),
        migrations.DeleteModel(
            name='Emision',
        ),
    ]
