# Generated by Django 3.2.5 on 2021-07-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd_clie',
            name='id',
        ),
        migrations.AlterField(
            model_name='bd_clie',
            name='Seudo',
            field=models.CharField(max_length=35, primary_key=True, serialize=False),
        ),
    ]
