# Generated by Django 3.2.5 on 2022-02-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0003_producto'),
        ('guia', '0003_auto_20220215_1122'),
        ('datos_g', '0003_alter_datos_g_id_pro'),
        ('base_cliente', '0002_auto_20220215_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_clie',
            name='id_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argumento.producto', verbose_name='Id producto'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
