# Generated by Django 3.2.5 on 2021-08-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0002_bd_clie_guia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_clie',
            name='guia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
