# Generated by Django 3.2.5 on 2022-03-24 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0001_initial'),
        ('base_cliente', '0002_bd_clie_fisico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd_clie',
            name='fisico',
        ),
        migrations.AddField(
            model_name='bd_clie',
            name='tipo_do',
            field=models.CharField(choices=[('0', 'Faltante'), ('1', 'Fisico'), ('2', 'No llego fisico')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bd_clie',
            name='nom_pro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='argumento.nom_producto', verbose_name='Nombre del producto'),
        ),
    ]
