# Generated by Django 3.2.5 on 2022-03-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0003_auto_20220324_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='No_fisico',
            fields=[
                ('seudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base_cliente.bd_clie')),
            ],
        ),
    ]
