# Generated by Django 3.2.5 on 2022-02-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0004_auto_20220215_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd_clie',
            name='guia',
        ),
    ]
