# Generated by Django 3.2.5 on 2022-03-24 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0004_no_fisico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='no_fisico',
            name='seudo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base_cliente.bd_clie'),
        ),
    ]
