# Generated by Django 3.2.5 on 2022-03-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0005_alter_no_fisico_seudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bd_clie',
            old_name='tipo_do',
            new_name='fisicos',
        ),
    ]
