# Generated by Django 3.2.5 on 2022-02-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0005_remove_bd_clie_guia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd_clie',
            name='bolsa',
        ),
    ]
