# Generated by Django 3.2.5 on 2022-02-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0006_remove_bd_clie_bolsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd_clie',
            name='orden',
        ),
    ]
