# Generated by Django 3.2.5 on 2022-04-01 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0001_initial'),
        ('base_cliente', '0006_rename_tipo_do_bd_clie_fisicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd_clie',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='argumento.producto'),
            preserve_default=False,
        ),
    ]
