# Generated by Django 3.2.5 on 2022-02-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0007_remove_bd_clie_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd_clie',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='bd_clie',
            name='d_i_a',
        ),
    ]
