# Generated by Django 3.2.5 on 2021-09-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0007_alter_bd_clie_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd_clie',
            name='author',
        ),
    ]
