# Generated by Django 3.2.5 on 2022-02-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0008_auto_20220215_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd_clie',
            name='ofi',
        ),
    ]
