# Generated by Django 3.2.5 on 2022-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0008_alter_bd_clie_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_clie',
            name='fisicos',
            field=models.CharField(choices=[('1', 'Fisico'), ('2', 'No llego fisico')], max_length=8),
        ),
    ]
