# Generated by Django 3.2.5 on 2022-06-24 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0011_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda_bd',
            fields=[
                ('id_agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agenda', serialize=False, to='base_cliente.bd_clie')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
