# Generated by Django 3.2.5 on 2022-02-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0012_auto_20220215_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_clie',
            name='fecha',
            field=models.DateField(),
        ),
    ]
