# Generated by Django 3.2.5 on 2022-07-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0013_alter_bd_clie_fisicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd_clie',
            name='telefono',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
