# Generated by Django 3.2.5 on 2021-11-12 18:54

import applications.guia.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('fisico', '0001_initial'),
        ('base_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cod_vis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de visita')),
                ('visita', models.CharField(max_length=36)),
                ('tipo', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('proceso', models.CharField(max_length=30)),
                ('cod_dir', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_serv', models.IntegerField(primary_key=True, serialize=False)),
                ('Servicio', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('fisico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='fisico.fisico')),
                ('seudo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guias', serialize=False, to='base_cliente.bd_clie')),
                ('postal', models.CharField(blank=True, max_length=7, null=True)),
                ('barrio', models.CharField(blank=True, max_length=70, null=True)),
                ('m', models.IntegerField(blank=True, default=1, null=True)),
                ('ancho', models.IntegerField(blank=True, default=1, null=True)),
                ('alto', models.IntegerField(blank=True, default=1, null=True)),
                ('largo', models.IntegerField(blank=True, default=1, null=True)),
                ('copia', models.IntegerField(blank=True, default=1, null=True)),
                ('unidad', models.IntegerField(blank=True, default=1, null=True)),
                ('contiene', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('domicilio', models.IntegerField(blank=True, default=0, null=True)),
                ('acarreo', models.IntegerField(blank=True, default=0, null=True)),
                ('flete', models.IntegerField(blank=True, default=0, null=True)),
                ('declarado', models.IntegerField(blank=True, default=0, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='guia')),
                ('cantidad_vi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cantidad visitas')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('id_clie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('id_ser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.servicio', verbose_name='Servicio')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_cliente.producto')),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guia',
                'ordering': ['-id_guia'],
            },
            bases=('fisico.fisico',),
            managers=[
                ('objects', applications.guia.models.LogEntryManager()),
            ],
        ),
    ]
