# Generated by Django 3.2.5 on 2021-08-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('base_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_est', models.IntegerField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_serv', models.IntegerField(primary_key=True, serialize=False)),
                ('Servicio', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id_tip', models.IntegerField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipo',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_mot', models.IntegerField()),
                ('Motivo', models.CharField(max_length=50)),
                ('id_tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia.tipo')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivo',
            },
        ),
        migrations.CreateModel(
            name='guia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Guia')),
                ('Bolsa', models.IntegerField()),
                ('Seudo', models.CharField(max_length=35)),
                ('m', models.IntegerField(blank=True, default=1, null=True)),
                ('Ancho', models.IntegerField(blank=True, default=1, null=True)),
                ('Alto', models.IntegerField(blank=True, default=1, null=True)),
                ('Largo', models.IntegerField(blank=True, default=1, null=True)),
                ('Copia', models.IntegerField(blank=True, default=1, null=True)),
                ('Unidad', models.IntegerField(blank=True, default=1, null=True)),
                ('Contiene', models.CharField(blank=True, max_length=50, null=True)),
                ('Orden', models.IntegerField(blank=True, null=True)),
                ('Domicilio', models.IntegerField(blank=True, default=0, null=True)),
                ('Acarreo', models.IntegerField(blank=True, default=0, null=True)),
                ('Flete', models.IntegerField(blank=True, default=0, null=True)),
                ('Declarado', models.IntegerField(blank=True, default=0, null=True)),
                ('Fecha', models.DateTimeField(blank=True, null=True)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='guia')),
                ('d_i', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_cliente.bd_clie')),
                ('id_clie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('id_est', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.estado')),
                ('id_mot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.motivo', verbose_name='id Motivo')),
                ('id_serv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.servicio')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_cliente.producto')),
            ],
            options={
                'verbose_name': 'guia',
                'verbose_name_plural': 'guia',
            },
        ),
    ]
