# Generated by Django 3.2.5 on 2022-02-07 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guia', '0001_initial'),
        ('courrier', '0001_initial'),
        ('cliente', '0001_initial'),
        ('datos_g', '0002_initial'),
        ('fisico', '0002_initial'),
        ('base_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='cod_vis',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guia.cod_vis'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='id_ciu',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cliente.ciudad', verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='id_clie',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='id_est',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guia.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='id_ser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='guia.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='mensajero',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courrier.courrier'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='mot',
            field=models.ForeignKey(blank=True, db_constraint=False, default=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datos_g.motivo', verbose_name='motivo'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='proceso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fisico.proceso'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base_cliente.producto'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='seudo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base_cliente.bd_clie'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='guia',
            name='id_clie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='guia',
            name='id_ser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='guia',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_cliente.producto'),
        ),
        migrations.AddField(
            model_name='guia',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
