# Generated by Django 3.2.5 on 2021-08-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='Bolsa',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='Seudo',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
