# Generated by Django 3.2.5 on 2021-07-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_cliente', '0002_auto_20210726_0836'),
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='d_i',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base_cliente.bd_clie'),
            preserve_default=False,
        ),
    ]
