# Generated by Django 3.2.5 on 2021-09-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad recepcion '),
        ),
    ]
