# Generated by Django 3.2.5 on 2021-08-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='Imagen',
            field=models.ImageField(blank=True, default='guia/', null=True, upload_to='guia'),
        ),
    ]
