# Generated by Django 3.2.5 on 2021-07-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_guia_d_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
