# Generated by Django 3.2.5 on 2022-02-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0003_alter_fisico_imagen'),
        ('guia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='id_guia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_mesa', to='fisico.fisico'),
        ),
    ]
