# Generated by Django 3.2.5 on 2022-01-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guia',
            options={'verbose_name': 'Guia', 'verbose_name_plural': 'Guia'},
        ),
    ]
