# Generated by Django 3.2.5 on 2022-02-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalguia',
            name='fecha_planilla',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
