# Generated by Django 3.2.5 on 2022-01-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedfile',
            name='feed',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.DeleteModel(
            name='FeedFile',
        ),
    ]
