# Generated by Django 3.2.5 on 2021-12-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0003_alter_guia_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='codigo',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
