# Generated by Django 3.2.5 on 2022-03-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0003_alter_historicalguia_fecha_planilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalguia',
            name='fecha_planilla',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
