# Generated by Django 3.2.5 on 2021-07-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0003_alter_guia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to='Imagen'),
        ),
    ]
