# Generated by Django 3.2.5 on 2021-09-10 03:51

import applications.guia.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0003_guia_usuario'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='guia',
            managers=[
                ('objects', applications.guia.models.LogEntryManager()),
            ],
        ),
    ]
