# Generated by Django 3.2.5 on 2022-02-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0003_alter_img_id_guia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalguia',
            name='imagen',
        ),
    ]
