# Generated by Django 3.2.5 on 2021-09-10 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0004_alter_guia_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guia',
            old_name='usuario',
            new_name='user',
        ),
    ]
