# Generated by Django 3.2.5 on 2022-02-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0004_delete_historicalimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalguia',
            name='id_guia',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='1000'),
        ),
    ]
