# Generated by Django 3.2.5 on 2022-03-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0007_alter_historicalguia_fecha_descargue'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalguia',
            name='destino',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='origen',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
