# Generated by Django 3.2.5 on 2022-04-05 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0009_historicalguia_fecha_bolsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='mod_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
