# Generated by Django 3.2.5 on 2022-04-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0002_motivo_call'),
        ('guia', '0010_img_mod_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='motivo_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.motivo_call'),
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='motivo_call',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='argumento.motivo_call'),
        ),
    ]
