# Generated by Django 3.2.5 on 2022-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0013_historicalguia_estado_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='observacion',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='observacion',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
