# Generated by Django 3.2.5 on 2022-05-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0015_auto_20220520_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='motivo_call',
        ),
        migrations.RemoveField(
            model_name='historicalguia',
            name='motivo_call',
        ),
    ]
