# Generated by Django 3.2.5 on 2022-05-22 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0016_auto_20220520_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guiap',
            fields=[
                ('seudof', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mascotas', models.IntegerField()),
                ('razones', models.TextField()),
                ('personap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia.guiap')),
            ],
        ),
    ]
