# Generated by Django 3.2.5 on 2022-05-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0017_guiap_telefonop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelefonoP',
        ),
    ]
