# Generated by Django 3.2.5 on 2022-06-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0018_delete_telefonop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='acarreo',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='copia',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='flete',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='m',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='historicalguia',
            name='acarreo',
        ),
        migrations.RemoveField(
            model_name='historicalguia',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='historicalguia',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='historicalguia',
            name='copia',
        ),
        migrations.RemoveField(
            model_name='historicalguia',
            name='flete',
        ),
        migrations.RemoveField(
            model_name='historicalguia',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='historicalguia',
            name='m',
        ),
        migrations.RemoveField(
            model_name='historicalguia',
            name='unidad',
        ),
    ]
