# Generated by Django 3.2.5 on 2022-06-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0020_auto_20220604_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guia',
            options={'verbose_name': 'Guia', 'verbose_name_plural': 'Buscar'},
        ),
        migrations.AlterModelOptions(
            name='historicalguia',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Guia'},
        ),
    ]
