# Generated by Django 3.2.5 on 2022-06-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0022_alter_guia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guia',
            options={'verbose_name': 'Guia', 'verbose_name_plural': ''},
        ),
    ]
