# Generated by Django 3.2.5 on 2022-06-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0026_auto_20220604_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='tel',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
