# Generated by Django 3.2.5 on 2022-06-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0027_guia_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='tel',
        ),
    ]
