# Generated by Django 3.2.5 on 2022-06-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0029_guia_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='id_clie',
        ),
        migrations.RemoveField(
            model_name='historicalguia',
            name='id_clie',
        ),
    ]
