# Generated by Django 3.2.5 on 2022-06-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0030_auto_20220606_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='numero',
        ),
        migrations.AddField(
            model_name='historicalguia',
            name='estado_img',
            field=models.CharField(blank=True, choices=[('E', 'ENTREGA'), ('D', 'ENTREGA DIGITALIZADA')], max_length=1, null=True),
        ),
    ]
