# Generated by Django 3.2.5 on 2022-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0032_alter_historicalguia_estado_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
