# Generated by Django 3.2.5 on 2022-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0035_auto_20220610_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='coberturapdf',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha cobertura'),
        ),
    ]
