# Generated by Django 3.2.5 on 2022-07-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0038_auto_20220705_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalguia',
            name='estado_img',
        ),
        migrations.AddField(
            model_name='img',
            name='estado_img',
            field=models.CharField(blank=True, choices=[('ENTREGA', 'ENTREGA'), ('ENTREGA_DIGITALIZADA', 'ENTREGA DIGITALIZADA')], max_length=22, null=True, verbose_name='gestion'),
        ),
    ]
