# Generated by Django 3.2.5 on 2022-07-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0039_auto_20220715_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='estado_img',
            field=models.CharField(blank=True, choices=[('ENTREGA_DIGITALIZADA', 'ENTREGA DIGITALIZADA')], default='ENTREGA_DIGITALIZADA', max_length=22, null=True, verbose_name='gestion'),
        ),
    ]
