# Generated by Django 3.2.5 on 2022-07-18 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_ciudad'),
        ('guia', '0040_alter_img_estado_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rastreo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('motivopr', models.CharField(max_length=30)),
            ],
        ),
    ]
