# Generated by Django 3.2.5 on 2022-07-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0042_alter_rastreo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastreo',
            name='id_guia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='guia.guia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rastreo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
