# Generated by Django 3.2.5 on 2022-07-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0044_alter_rastreo_id_guia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastreo',
            name='motivopr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
