# Generated by Django 3.2.5 on 2022-07-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0046_rastreo_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rastreo',
        ),
    ]
