# Generated by Django 3.2.5 on 2021-07-15 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciu', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Ciudad', models.CharField(max_length=80)),
                ('dep', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudad',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_clie', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id cliente')),
                ('nit', models.CharField(max_length=20)),
                ('R_s', models.CharField(max_length=70, verbose_name='Razon social')),
                ('Contact', models.CharField(max_length=50, verbose_name='Contacto')),
                ('dir', models.CharField(max_length=120, verbose_name='Direccion')),
                ('tel', models.IntegerField(verbose_name='Tel fijo')),
                ('Cel', models.IntegerField(verbose_name='Celular')),
                ('ind', models.IntegerField(verbose_name='Indicativo')),
                ('Radicacion', models.IntegerField()),
                ('Fact', models.CharField(max_length=4, verbose_name='Factura')),
                ('id_ciu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad', verbose_name='Id ciudad')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Cliente',
            },
        ),
    ]
