# Generated by Django 3.2.5 on 2021-07-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='id_ciu',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
