# Generated by Django 3.2.5 on 2022-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficinas',
            name='fusionada',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
