# Generated by Django 3.2.5 on 2022-01-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_clie',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Id cliente'),
        ),
    ]
