# Generated by Django 3.2.5 on 2022-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_oficinas_fusionada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficinas',
            name='hora_adi',
            field=models.CharField(max_length=30, verbose_name='Horario adicional'),
        ),
        migrations.AlterField(
            model_name='oficinas',
            name='hora_norm',
            field=models.CharField(max_length=30, verbose_name='Horario normal'),
        ),
        migrations.AlterField(
            model_name='oficinas',
            name='hora_sab',
            field=models.CharField(max_length=30, verbose_name='Horario sabado'),
        ),
    ]
