# Generated by Django 3.2.5 on 2022-03-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20220303_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficinas',
            name='num_dia_entr',
            field=models.CharField(max_length=8, verbose_name='N° Días Entrega_(hábiles)'),
        ),
    ]
