# Generated by Django 3.2.5 on 2022-03-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_oficinas_num_dia_entr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficinas',
            name='hora_adi',
            field=models.CharField(max_length=35, verbose_name='Horario adicional'),
        ),
        migrations.AlterField(
            model_name='oficinas',
            name='hora_norm',
            field=models.CharField(max_length=35, verbose_name='Horario normal'),
        ),
        migrations.AlterField(
            model_name='oficinas',
            name='hora_sab',
            field=models.CharField(max_length=35, verbose_name='Horario sabado'),
        ),
    ]
