# Generated by Django 3.2.5 on 2022-05-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20220503_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['ciudad']},
        ),
    ]
