# Generated by Django 3.2.5 on 2021-07-28 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_g',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seudo', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=255)),
                ('postal', models.CharField(max_length=7)),
                ('barrio', models.CharField(blank=True, max_length=70, null=True)),
                ('gx', models.BigIntegerField(blank=True, null=True)),
                ('gy', models.BigIntegerField(blank=True, null=True)),
                ('id_ciu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad', verbose_name='Id ciudad')),
                ('id_mot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.motivo', verbose_name='Id motivo')),
            ],
            options={
                'verbose_name': 'Datos de gestion',
                'verbose_name_plural': 'Datos de gestion',
            },
        ),
    ]
