# Generated by Django 3.2.5 on 2022-02-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fisico', '0001_initial'),
        ('cliente', '0001_initial'),
        ('guia', '0001_initial'),
        ('datos_g', '0001_initial'),
        ('base_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('orden', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tip', models.IntegerField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipo',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=50)),
                ('id_tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_g.tipo')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivo',
            },
        ),
        migrations.CreateModel(
            name='datos_g',
            fields=[
                ('seudo_dg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guia.guia')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha fisico')),
                ('d_i', models.BigIntegerField(blank=True, null=True, verbose_name='Documento de identidad')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('dest', models.CharField(blank=True, max_length=100, null=True)),
                ('d_i_a', models.IntegerField(blank=True, null=True, verbose_name='CC autorizado')),
                ('autor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autorizado')),
                ('postal', models.CharField(blank=True, max_length=7, null=True)),
                ('barrio', models.CharField(blank=True, max_length=70, null=True)),
                ('marca', models.CharField(blank=True, max_length=15, null=True)),
                ('gx', models.BigIntegerField(blank=True, null=True)),
                ('gy', models.BigIntegerField(blank=True, null=True)),
                ('lote', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('zona', models.CharField(blank=True, max_length=30, null=True)),
                ('oficina', models.CharField(max_length=5)),
                ('cod_vis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.cod_vis')),
                ('id_ciu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.ciudad', verbose_name='Id ciudad')),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.estado', verbose_name='Estado')),
                ('id_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_cliente.producto')),
                ('mot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_g.motivo', verbose_name='motivo')),
                ('orimp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_g.orden', verbose_name='Orden impre')),
                ('proc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fisico.proceso', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Datos de gestion',
                'verbose_name_plural': 'Datos de gestion',
            },
        ),
        migrations.AddField(
            model_name='cubrimiento',
            name='dane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ciudad', to='cliente.ciudad'),
        ),
    ]
