# Generated by Django 3.2.5 on 2021-11-12 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0002_guia_user'),
        ('datos_g', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_g',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.proceso'),
        ),
    ]
