# Generated by Django 3.2.5 on 2022-02-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0003_producto'),
        ('datos_g', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_g',
            name='id_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.producto'),
        ),
    ]
