# Generated by Django 3.2.5 on 2021-12-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
            ],
        ),
    ]
