# Generated by Django 3.2.5 on 2022-02-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_g',
            name='d_i_a',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CC autorizado'),
        ),
    ]
