# Generated by Django 3.2.5 on 2022-01-25 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('datos_g', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cubrimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cubrimiento', models.IntegerField(verbose_name='Codigo')),
                ('oficina', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=5)),
                ('direccion_cita', models.CharField(max_length=180)),
                ('postal', models.IntegerField()),
                ('dane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ciudad', to='cliente.ciudad')),
            ],
        ),
    ]
