# Generated by Django 3.2.5 on 2021-11-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_g',
            name='id_datos_g',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
