# Generated by Django 3.2.5 on 2021-12-30 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0003_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_g',
            name='orimp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos_g.orden', verbose_name='Orden impre '),
        ),
    ]
