# Generated by Django 3.2.5 on 2022-01-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0003_cubrimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cubrimiento',
            name='id',
        ),
        migrations.AlterField(
            model_name='cubrimiento',
            name='id_cubrimiento',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
