# Generated by Django 3.2.5 on 2022-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0004_auto_20220125_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubrimiento',
            name='oficina',
            field=models.CharField(max_length=80),
        ),
    ]
