# Generated by Django 3.2.5 on 2022-04-28 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos_g', '0004_orden_nombre_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_g',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario_datog'),
        ),
    ]
