# Generated by Django 3.2.5 on 2022-02-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0004_est_clie'),
        ('datos_g', '0004_alter_datos_g_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_g',
            name='id_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.producto', verbose_name='Producto'),
        ),
    ]
