# Generated by Django 3.2.5 on 2022-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0005_alter_datos_g_id_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_g',
            name='dest',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Destinatario'),
        ),
    ]
