# Generated by Django 3.2.5 on 2022-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0005_alter_cubrimiento_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubrimiento',
            name='dias',
            field=models.CharField(max_length=6),
        ),
    ]
