# Generated by Django 3.2.5 on 2022-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0006_alter_cubrimiento_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
