# Generated by Django 3.2.5 on 2022-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0007_orden_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
