# Generated by Django 3.2.5 on 2022-05-20 14:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0006_remove_tipo_tipo'),
        ('datos_g', '0007_alter_datos_g_orimp'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_g',
            name='fecha_call',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_g',
            name='motivo_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.motivo_call'),
        ),
        migrations.AddField(
            model_name='datos_g',
            name='observacion',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
