# Generated by Django 3.2.5 on 2022-02-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0003_auto_20220215_1122'),
        ('datos_g', '0007_remove_datos_g_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_g',
            name='seudo_dg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guia_d_g', serialize=False, to='guia.guia'),
        ),
    ]
