# Generated by Django 3.2.5 on 2022-01-31 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0003_auto_20220118_1553'),
        ('datos_g', '0008_alter_orden_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_g',
            name='id_datos_g',
        ),
        migrations.AlterField(
            model_name='datos_g',
            name='seudo_dg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guia.guia'),
            preserve_default=False,
        ),
    ]
