# Generated by Django 3.2.5 on 2022-06-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0030_auto_20220606_0926'),
        ('datos_g', '0009_auto_20220520_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agenda', serialize=False, to='guia.guia')),
            ],
        ),
    ]
