# Generated by Django 3.2.5 on 2022-01-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0009_auto_20220131_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='id',
        ),
        migrations.AlterField(
            model_name='orden',
            name='orden',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
