# Generated by Django 3.2.5 on 2022-07-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0010_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_g',
            name='postal',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
