# Generated by Django 3.2.5 on 2022-07-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0011_alter_datos_g_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tipo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
