# Generated by Django 3.2.5 on 2021-08-12 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='indicativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.IntegerField(verbose_name='Indicativo')),
                ('Region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='datos_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
                ('Activo', models.BooleanField(default=True)),
                ('d_i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia.guia')),
                ('id_mot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia.motivo')),
                ('indicativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call.indicativo')),
            ],
        ),
    ]
