# Generated by Django 3.2.5 on 2021-07-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_t',
            name='indicativo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='call.indicativo'),
            preserve_default=False,
        ),
    ]
