# Generated by Django 3.2.5 on 2021-07-26 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0004_alter_guia_imagen'),
        ('call', '0002_datos_t_indicativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_t',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datos_t',
            name='id_mot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guia.motivo'),
            preserve_default=False,
        ),
    ]
