# Generated by Django 3.2.5 on 2021-11-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_g', '0002_initial'),
        ('call', '0004_auto_20211130_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_t',
            name='d_i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_g.datos_g', verbose_name='Seudo buscar'),
        ),
        migrations.AlterField(
            model_name='historicaldatos_t',
            name='d_i',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datos_g.datos_g', verbose_name='Seudo buscar'),
        ),
    ]
