# Generated by Django 3.2.5 on 2022-05-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_alter_indicativo_ind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='calificacion_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_1', to='call.calificacion'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='calificacion_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_2', to='call.calificacion'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='calificacion_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_3', to='call.calificacion'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='calificacion_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_4', to='call.calificacion'),
        ),
    ]
