# Generated by Django 3.2.5 on 2022-05-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_auto_20220516_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='calificacion_5',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, null=True),
        ),
    ]
