# Generated by Django 3.2.5 on 2021-11-30 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_auto_20211130_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='telefono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='call.telefono'),
            preserve_default=False,
        ),
    ]
