# Generated by Django 3.2.5 on 2022-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0006_alter_auditoria_calificacion_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='observacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
