# Generated by Django 3.2.5 on 2022-05-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0007_alter_auditoria_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='estado_llamada',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
