# Generated by Django 3.2.5 on 2022-05-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0009_auditoria_motivo_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='estado_llamada',
        ),
    ]
