# Generated by Django 3.2.5 on 2022-05-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0010_remove_auditoria_estado_llamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='pregunta_1',
            field=models.ForeignKey(blank=True, default='pueba', null=True, on_delete=django.db.models.deletion.CASCADE, to='call.pregunta'),
        ),
    ]
