# Generated by Django 3.2.5 on 2022-05-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0011_alter_auditoria_pregunta_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='pregunta_1',
            field=models.ForeignKey(blank=True, default='puebass', null=True, on_delete=django.db.models.deletion.CASCADE, to='call.pregunta'),
        ),
    ]
