# Generated by Django 3.2.5 on 2022-05-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0013_alter_auditoria_pregunta_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='pregunta_1',
            field=models.CharField(blank=True, default='CUENTA USTED YA CON LA TC', max_length=70, null=True),
        ),
    ]
