# Generated by Django 3.2.5 on 2022-05-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0014_alter_auditoria_pregunta_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='pregunta_2',
            field=models.CharField(blank=True, default='BOLSA DEBIDAMENTE SELLADA', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='pregunta_3',
            field=models.CharField(blank=True, default='SOLICITO SU DOCUMENTO DE IDENTIDAD', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='pregunta_4',
            field=models.CharField(blank=True, default='FIRMO USTED EL ACUSE DE RECIBIDO', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='pregunta_5',
            field=models.CharField(blank=True, default='CALIFIQUE DE 1 A 5 EL SERVICIO', max_length=70, null=True),
        ),
    ]
