# Generated by Django 3.2.5 on 2022-05-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0016_telefono_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
