# Generated by Django 3.2.5 on 2022-05-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0006_remove_tipo_tipo'),
        ('call', '0018_telefono_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='motivo_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.motivo_call'),
        ),
    ]
