# Generated by Django 3.2.5 on 2022-05-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0019_telefono_motivo_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefono',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='motivo_call',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='observacion',
        ),
    ]
