# Generated by Django 3.2.5 on 2022-05-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0016_auto_20220520_0827'),
        ('call', '0022_telefono_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='id',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guia_id', serialize=False, to='guia.guia'),
        ),
    ]
