# Generated by Django 3.2.5 on 2022-05-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0017_guiap_telefonop'),
        ('call', '0026_alter_telefono_fecha_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='id',
            field=models.OneToOneField(max_length=12, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_query_name='telefono_guia', serialize=False, to='guia.guia'),
        ),
    ]
