# Generated by Django 3.2.5 on 2022-07-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_ciudad'),
        ('call', '0027_alter_telefono_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='informe_call',
            fields=[
                ('id_telefono', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
            ],
        ),
    ]
