# Generated by Django 3.2.5 on 2022-07-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0028_informe_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe_call',
            old_name='id_telefono',
            new_name='id',
        ),
    ]
