# Generated by Django 3.2.5 on 2022-07-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0029_rename_id_telefono_informe_call_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe_call',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='call.telefono'),
        ),
    ]
