# Generated by Django 3.2.5 on 2022-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0030_alter_informe_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe_call',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
