# Generated by Django 3.2.5 on 2022-07-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0031_informe_call_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='estado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
