# Generated by Django 3.2.5 on 2022-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0032_telefono_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
