# Generated by Django 3.2.5 on 2022-07-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guia', '0047_delete_rastreo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rastreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivopr', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guia.guia')),
            ],
        ),
    ]
