# Generated by Django 3.2.5 on 2022-07-18 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0025_auto_20220715_0900'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastreo',
            name='id_fisico_track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fisco_tracking', to='fisico.fisico'),
            preserve_default=False,
        ),
    ]
