# Generated by Django 3.2.5 on 2022-07-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisico', '0025_auto_20220715_0900'),
        ('guia', '0047_delete_rastreo'),
        ('tracking', '0002_rastreo_id_fisico_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastreo',
            name='id_fisico_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fisco_tracking', to='fisico.fisico'),
        ),
        migrations.AlterField(
            model_name='rastreo',
            name='id_guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guia.guia'),
        ),
    ]
