# Generated by Django 3.2.5 on 2022-07-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20220718_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastreo',
            name='guia_tracking',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
