# Generated by Django 3.2.5 on 2022-07-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_rastreo_guia_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastreo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
