# Generated by Django 3.2.5 on 2022-07-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_rastreo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastreo',
            name='guia_tracking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
