# Generated by Django 3.2.5 on 2022-07-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0047_delete_rastreo'),
        ('tracking', '0006_alter_rastreo_guia_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastreo',
            name='id_guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackin_guia', to='guia.guia'),
        ),
    ]
