# Generated by Django 3.2.5 on 2022-07-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0009_alter_cod_vis_id'),
        ('tracking', '0007_alter_rastreo_id_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastreo',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.estado'),
        ),
    ]
