# Generated by Django 3.2.5 on 2022-02-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqr',
            name='otro_cual',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
