# Generated by Django 3.2.5 on 2022-02-15 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cod_vis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de visita')),
                ('visita', models.CharField(max_length=36)),
                ('tipo', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Nom_producto',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('proceso', models.CharField(max_length=30)),
                ('cod_dir', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tip', models.IntegerField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipo',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=50)),
                ('id_tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='argumento.tipo')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivo',
            },
        ),
    ]
