# Generated by Django 3.2.5 on 2022-04-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=35)),
            ],
        ),
    ]
