# Generated by Django 3.2.5 on 2022-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emision',
            fields=[
                ('t_emi', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Tipo emision')),
                ('emision', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name': 'Emision',
                'verbose_name_plural': 'Emision',
            },
        ),
    ]
