# Generated by Django 3.2.5 on 2022-02-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nom_producto',
            name='nom_producto',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
