# Generated by Django 3.2.5 on 2022-05-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0002_motivo_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivo',
            name='estado_call',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
