# Generated by Django 3.2.5 on 2022-05-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0003_motivo_estado_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivo',
            name='estado_call',
        ),
    ]
