# Generated by Django 3.2.5 on 2022-05-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0004_remove_motivo_estado_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
