# Generated by Django 3.2.5 on 2022-05-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0005_tipo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='Tipo',
        ),
    ]
