# Generated by Django 3.2.5 on 2022-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0006_remove_tipo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivo_call',
            name='tipificacion',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
    ]
