# Generated by Django 3.2.5 on 2022-05-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0007_motivo_call_tipificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='franquicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franqucia', models.CharField(max_length=30)),
            ],
        ),
    ]
