# Generated by Django 3.2.5 on 2022-07-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argumento', '0008_franquicia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cod_vis',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Codigo de visita'),
        ),
    ]
